### ISSUE TITLE
Cannot roslaunch 

### ISSUE THREAD

**Issue by BKC92** [SMRazaRizvi96/MR-based-drone-controller#4]
Hi Raza
An error occurred while following your project, but I couldn't figure it out even after searching, so I asked this question. My problem is that when I run roslaunch, the following error appears and ends with keyboardinterrupt. I would be very grateful if you could tell me how to fix the error.

roslaunch drone_control joy_node.launch 
... logging to /home/user/.ros/log/e8d9fcf6-ece5-11ed-b933-55d41ac45852/roslaunch-user-VirtualBox-2232.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://user-VirtualBox:38317/

SUMMARY
========

PARAMETERS
 * /aruco_single/camera_frame: stereo_gazebo_lef...
 * /aruco_single/corner_refinement: LINES
 * /aruco_single/image_is_rectified: True
 * /aruco_single/marker_frame: aruco_marker_frame
 * /aruco_single/marker_id: 582
 * /aruco_single/marker_size: 0.034
 * /aruco_single/reference_frame: 
 * /joy_node/dev: /dev/input/js6
 * /rosdistro: noetic
 * /rosversion: 1.16.0
 * /tello/image_raw/image_transport: h264
 * /tello/new_tello_driver_node/camera_calibration: /home/user/catki...
 * /tello/new_tello_driver_node/connect_timeout_sec: 10.0
 * /tello/new_tello_driver_node/local_cmd_client_port: 8890
 * /tello/new_tello_driver_node/local_vid_server_port: 6038
 * /tello/new_tello_driver_node/stream_h264_video: True
 * /tello/new_tello_driver_node/tello_cmd_server_port: 8889
 * /tello/new_tello_driver_node/tello_ip: 192.168.10.3

NODES
  /
    aruco_single (aruco_ros/single)
    joy_node (joy/joy_node)
    tello_NEW_Aruco_Pose (drone_control/tello_NEW_Aruco_Pose.py)
    tello_joypad_control (drone_control/tello_joypad_control.py)
  /tello/
    image_raw (image_transport/republish)
    new_tello_driver_node (drone_control/new_tello_driver_node.py)

ROS_MASTER_URI=http://localhost:11311

process[aruco_single-1]: started with pid [2246]
process[tello/new_tello_driver_node-2]: started with pid [2247]
process[tello/image_raw-3]: started with pid [2248]
process[tello_NEW_Aruco_Pose-4]: started with pid [2249]
process[joy_node-5]: started with pid [2250]
RLException: Roslaunch got a 'No such file or directory' error while attempting to run:

xterm -e /home/user/catkin_ws/src/drone_control/src/tello_joypad_control.py __name:=tello_joypad_control __log:=/home/user/.ros/log/e8d9fcf6-ece5-11ed-b933-55d41ac45852/tello_joypad_control-6.log

Please make sure that all the executables in this command exist and have
executable permission. This is often caused by a bad launch-prefix.
The traceback for the exception was written to the log file
[ERROR] [1683471112.055065609]: Couldn't open joystick /dev/input/js6. Will retry every second.
[tello_joypad_control-6] killing on exit
[joy_node-5] killing on exit
[tello_NEW_Aruco_Pose-4] killing on exit
[tello/image_raw-3] killing on exit
[aruco_single-1] killing on exit
[tello/new_tello_driver_node-2] killing on exit
Traceback (most recent call last):
  File "/home/user/catkin_ws/src/drone_control/src/tello_NEW_Aruco_Pose.py", line 13, in <module>
    import actionlib
  File "/opt/ros/noetic/lib/python3/dist-packages/actionlib/__init__.py", line 28, in <module>
    from actionlib.action_client import *
  File "/opt/ros/noetic/lib/python3/dist-packages/actionlib/action_client.py", line 56, in <module>
    import rospy
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/__init__.py", line 47, in <module>
    from std_msgs.msg import Header
  File "/opt/ros/noetic/lib/python3/dist-packages/std_msgs/msg/__init__.py", line 1, in <module>
    from ._Bool import *
  File "/opt/ros/noetic/lib/python3/dist-packages/std_msgs/msg/_Bool.py", line 6, in <module>
    import genpy
  File "/opt/ros/noetic/lib/python3/dist-packages/genpy/__init__.py", line 34, in <module>
    from . message import Message, SerializationError, DeserializationError, MessageException, struct_I
  File "/opt/ros/noetic/lib/python3/dist-packages/genpy/message.py", line 64, in <module>
    import numpy as np
  File "/usr/lib/python3/dist-packages/numpy/__init__.py", line 142, in <module>
    from . import core
  File "/usr/lib/python3/dist-packages/numpy/core/__init__.py", line 17, in <module>
    from . import multiarray
  File "/usr/lib/python3/dist-packages/numpy/core/multiarray.py", line 14, in <module>
    from . import overrides
  File "/usr/lib/python3/dist-packages/numpy/core/overrides.py", line 5, in <module>
    import textwrap
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
Traceback (most recent call last):
  File "/home/user/catkin_ws/src/drone_control/src/new_tello_driver_node.py", line 2, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 914, in _find_spec
    import rospy
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/__init__.py", line 47, in <module>
  File "<frozen importlib._bootstrap_external>", line 1407, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1379, in _get_spec
    from std_msgs.msg import Header
  File "/opt/ros/noetic/lib/python3/dist-packages/std_msgs/msg/__init__.py", line 1, in <module>
  File "<frozen importlib._bootstrap_external>", line 1534, in find_spec
    from ._Bool import *
  File "/opt/ros/noetic/lib/python3/dist-packages/std_msgs/msg/_Bool.py", line 6, in <module>
    import genpy
  File "<frozen importlib._bootstrap_external>", line 121, in _path_join
  File "/opt/ros/noetic/lib/python3/dist-packages/genpy/__init__.py", line 34, in <module>
KeyboardInterrupt
    from . message import Message, SerializationError, DeserializationError, MessageException, struct_I
  File "/opt/ros/noetic/lib/python3/dist-packages/genpy/message.py", line 64, in <module>
    import numpy as np
  File "/usr/lib/python3/dist-packages/numpy/__init__.py", line 142, in <module>
    from . import core
  File "/usr/lib/python3/dist-packages/numpy/core/__init__.py", line 17, in <module>
    from . import multiarray
  File "/usr/lib/python3/dist-packages/numpy/core/multiarray.py", line 470, in <module>
    def can_cast(from_, to, casting=None):
  File "/usr/lib/python3/dist-packages/numpy/core/overrides.py", line 201, in decorator
    return array_function_dispatch(
  File "/usr/lib/python3/dist-packages/numpy/core/overrides.py", line 184, in decorator
    public_api = scope[implementation.__name__]
KeyboardInterrupt

---------------------------------------------------------------------------------------------------------------------

roslaunch drone_control MR-Drone-Controller.launch 
... logging to /home/user/.ros/log/e8d9fcf6-ece5-11ed-b933-55d41ac45852/roslaunch-user-VirtualBox-2080.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://user-VirtualBox:40261/

SUMMARY
========

PARAMETERS
 * /aruco_single/camera_frame: stereo_gazebo_lef...
 * /aruco_single/corner_refinement: LINES
 * /aruco_single/image_is_rectified: True
 * /aruco_single/marker_frame: aruco_marker_frame
 * /aruco_single/marker_id: 582
 * /aruco_single/marker_size: 0.034
 * /aruco_single/reference_frame: 
 * /rosdistro: noetic
 * /rosversion: 1.16.0
 * /tello/image_raw/image_transport: h264
 * /tello/new_tello_driver_node/camera_calibration: /home/user/catki...
 * /tello/new_tello_driver_node/connect_timeout_sec: 10.0
 * /tello/new_tello_driver_node/local_cmd_client_port: 8890
 * /tello/new_tello_driver_node/local_vid_server_port: 6038
 * /tello/new_tello_driver_node/stream_h264_video: True
 * /tello/new_tello_driver_node/tello_cmd_server_port: 8889
 * /tello/new_tello_driver_node/tello_ip: 192.168.10.3
 * /unity_endpoint/tcp_ip: 0.0.0.0
 * /unity_endpoint/tcp_port: 10000

NODES
  /
    aruco_single (aruco_ros/single)
    tello_Final_Controller (drone_control/tello_Final_Controller.py)
    tello_NEW_Aruco_Pose (drone_control/tello_NEW_Aruco_Pose.py)
    unity_endpoint (ros_tcp_endpoint/default_server_endpoint.py)
  /tello/
    image_raw (image_transport/republish)
    new_tello_driver_node (drone_control/new_tello_driver_node.py)

ROS_MASTER_URI=http://localhost:11311

process[unity_endpoint-1]: started with pid [2094]
process[aruco_single-2]: started with pid [2095]
process[tello/new_tello_driver_node-3]: started with pid [2096]
process[tello/image_raw-4]: started with pid [2097]
process[tello_NEW_Aruco_Pose-5]: started with pid [2098]
RLException: Roslaunch got a 'No such file or directory' error while attempting to run:

xterm -e /home/user/catkin_ws/src/drone_control/src/tello_Final_Controller.py __name:=tello_Final_Controller __log:=/home/user/.ros/log/e8d9fcf6-ece5-11ed-b933-55d41ac45852/tello_Final_Controller-6.log

Please make sure that all the executables in this command exist and have
executable permission. This is often caused by a bad launch-prefix.
The traceback for the exception was written to the log file
[tello_Final_Controller-6] killing on exit
[tello_NEW_Aruco_Pose-5] killing on exit
Traceback (most recent call last):
  File "/home/user/catkin_ws/src/drone_control/src/tello_NEW_Aruco_Pose.py", line 13, in <module>
    import actionlib
  File "/opt/ros/noetic/lib/python3/dist-packages/actionlib/__init__.py", line 28, in <module>
    from actionlib.action_client import *
  File "/opt/ros/noetic/lib/python3/dist-packages/actionlib/action_client.py", line 56, in <module>
    import rospy
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/__init__.py", line 47, in <module>
    from std_msgs.msg import Header
  File "/opt/ros/noetic/lib/python3/dist-packages/std_msgs/msg/__init__.py", line 1, in <module>
    from ._Bool import *
  File "/opt/ros/noetic/lib/python3/dist-packages/std_msgs/msg/_Bool.py", line 6, in <module>
    import genpy
  File "/opt/ros/noetic/lib/python3/dist-packages/genpy/__init__.py", line 34, in <module>
    from . message import Message, SerializationError, DeserializationError, MessageException, struct_I
  File "/opt/ros/noetic/lib/python3/dist-packages/genpy/message.py", line 43, in <module>
    import struct
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 914, in _find_spec
  File "<frozen importlib._bootstrap>", line 802, in find_spec
KeyboardInterrupt
[tello/image_raw-4] killing on exit
[tello/new_tello_driver_node-3] killing on exit
[aruco_single-2] killing on exit
Traceback (most recent call last):
  File "/home/user/catkin_ws/src/drone_control/src/new_tello_driver_node.py", line 2, in <module>
[unity_endpoint-1] killing on exit
    import rospy
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/__init__.py", line 47, in <module>
    from std_msgs.msg import Header
  File "/opt/ros/noetic/lib/python3/dist-packages/std_msgs/msg/__init__.py", line 1, in <module>
    from ._Bool import *
  File "/opt/ros/noetic/lib/python3/dist-packages/std_msgs/msg/_Bool.py", line 6, in <module>
    import genpy
  File "/opt/ros/noetic/lib/python3/dist-packages/genpy/__init__.py", line 34, in <module>
    from . message import Message, SerializationError, DeserializationError, MessageException, struct_I
  File "/opt/ros/noetic/lib/python3/dist-packages/genpy/message.py", line 64, in <module>
    import numpy as np
  File "/usr/lib/python3/dist-packages/numpy/__init__.py", line 142, in <module>
Traceback (most recent call last):
  File "/home/user/catkin_ws/src/ROS-TCP-Endpoint/src/ros_tcp_endpoint/default_server_endpoint.py", line 3, in <module>
    from . import core
  File "/usr/lib/python3/dist-packages/numpy/core/__init__.py", line 71, in <module>
    import rospy
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/__init__.py", line 47, in <module>
    from . import numeric
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 844, in exec_module
  File "<frozen importlib._bootstrap_external>", line 939, in get_code
  File "<frozen importlib._bootstrap_external>", line 1038, in get_data
KeyboardInterrupt
    from std_msgs.msg import Header
  File "/opt/ros/noetic/lib/python3/dist-packages/std_msgs/msg/__init__.py", line 1, in <module>
    from ._Bool import *
  File "/opt/ros/noetic/lib/python3/dist-packages/std_msgs/msg/_Bool.py", line 6, in <module>
    import genpy
  File "/opt/ros/noetic/lib/python3/dist-packages/genpy/__init__.py", line 34, in <module>
    from . message import Message, SerializationError, DeserializationError, MessageException, struct_I
  File "/opt/ros/noetic/lib/python3/dist-packages/genpy/message.py", line 64, in <module>
    import numpy as np
  File "/usr/lib/python3/dist-packages/numpy/__init__.py", line 142, in <module>
    from . import core
  File "/usr/lib/python3/dist-packages/numpy/core/__init__.py", line 84, in <module>
    from . import getlimits
  File "/usr/lib/python3/dist-packages/numpy/core/getlimits.py", line 16, in <module>
    from . import umath
  File "<frozen importlib._bootstrap>", line 392, in parent
KeyboardInterrupt

**Comment by SMRazaRizvi96** [comment]
Seems to be an error of the ROS executor not able to find the binaries for all the node .py nodes in the current workspace overlay.

Try:

1. Building the ROS workspace again
2. Set the permissions for all the .py node by running:
`chmod +x <filename>.py`
3. Source the workspace

Then try to launch the launch file again.

**Comment by SMRazaRizvi96** [comment]
Closing due to no activity.
